"""sync subscription_plans schema

Revision ID: 74666597e362
Revises: 8f4d8d27c0b2
Create Date: 2026-04-24 11:24:37.225384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74666597e362'
down_revision: Union[str, None] = '8f4d8d27c0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('subscription_plans', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscription_plans', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'subscription_plans', ['name'])
    op.drop_column('subscription_plans', 'max_renewals')
    op.drop_column('subscription_plans', 'max_books_per_month')
    op.drop_column('subscription_plans', 'price_per_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('price_per_month', mysql.FLOAT(), nullable=False))
    op.add_column('subscription_plans', sa.Column('max_books_per_month', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscription_plans', sa.Column('max_renewals', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscription_plans', type_='unique')
    op.alter_column('subscription_plans', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscription_plans', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('subscription_plans', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
